<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Additional Information') ?></span></legend>
    <div class="field notification_phone_number required">
        <label for="notification_phone_number" class="label"><span><?php /* @escapeNotVerified */ echo __('My Attribute') ?></span></label>
        <div class="control">
            <input type="text" name="notification_phone_number" id="notification_phone_number" title="<?php /* @escapeNotVerified */ echo __('My Attribute') ?>" class="input-text" data-validate="{required:true}" autocomplete="off">
        </div>
    </div>
</fieldset>